name: Job Scraping Daily Run

on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 */2 * *" # Every 2 days at 10:00 IST

jobs:
  run-job-scraping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download tracker artifact
        uses: actions/download-artifact@v4
        with:
          name: processed-jobs-tracker
          path: .
        continue-on-error: true
      - name: Restore tracker file if present
        run: |
          if [ -f processed-jobs-tracker/processed_jobs.json ]; then
            mv processed-jobs-tracker/processed_jobs.json processed_jobs.json
            echo "Restored processed_jobs.json from artifact"
          fi
        shell: bash
      - name: Download parsed resume artifact
        uses: actions/download-artifact@v4
        with:
          name: parsed-resume
          path: .
        continue-on-error: true
      - name: Restore parsed resume file if present
        run: |
          if [ -f parsed_resume.json ]; then
            echo "Restored parsed_resume.json from artifact"
          else
            echo "No previous parsed resume artifact found — will re-parse"
          fi
        shell: bash

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v1
      - name: Cache sentence-transformers models
        uses: actions/cache@v4
        with:
          path: ~/.cache/torch/sentence_transformers
          key: ${{ runner.os }}-sentencetransformers-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-sentencetransformers-
      - name: Install dependencies with uv
        run: uv sync

      - name: Cache apt packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: >-
            texlive-latex-base
            texlive-latex-extra
            texlive-fonts-recommended
            texlive-fonts-extra
            texlive-font-utils
            fonts-roboto
          version: 1.0

      - name: Install TeX Live
        run: |
          sudo apt-get install -y --no-install-recommends \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-font-utils \
            fonts-roboto
        shell: bash

      - name: Create .env from repository secrets
        run: |
          cat > .env <<EOF
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          ZYTE_API_KEY=${{ secrets.ZYTE_API_KEY }}
          EMAIL_SMTP_HOST=${{ secrets.EMAIL_SMTP_HOST }}
          EMAIL_SMTP_PORT=${{ secrets.EMAIL_SMTP_PORT }}
          EMAIL_SENDER_ADDRESS=${{ secrets.EMAIL_SENDER_ADDRESS }}
          EMAIL_SENDER_PASSWORD=${{ secrets.EMAIL_SENDER_PASSWORD }}
          EMAIL_TO=${{ secrets.EMAIL_TO }}
          EOF
        shell: bash
      - name: Ensure processed_jobs.json exists
        run: |
          if [ ! -f processed_jobs.json ]; then
            echo "[]" > processed_jobs.json
            echo "Created empty processed_jobs.json"
          fi
        shell: bash
      - name: Run AI Job Application Assistant
        run: uv run python main.py
        shell: bash
      - name: Upload tracker artifact
        uses: actions/upload-artifact@v4
        with:
          name: processed-jobs-tracker
          path: processed_jobs.json
      - name: Upload parsed resume artifact
        uses: actions/upload-artifact@v4
        with:
          name: parsed-resume
          path: parsed_resume.json