name: Job Scraping Daily Run

on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 */2 * *" # every 2 days at 10:00 IST (adjust to */3 if you prefer every 3 days)

jobs:
  run-job-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download tracker artifact (if any)
        uses: actions/download-artifact@v4
        with:
          name: processed-jobs-tracker
          path: processed-jobs-tracker
          if-no-files-found: ignore

      - name: Restore tracker file if present
        run: |
          if [ -f processed-jobs-tracker/processed_jobs.json ]; then
            mv processed-jobs-tracker/processed_jobs.json processed_jobs.json
            echo "Restored processed_jobs.json from artifact"
          else
            echo "No previous tracker artifact found — starting fresh"
          fi
        shell: bash

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install TeX Live + fonts (optimized)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-font-utils \
            fonts-roboto || true
        # fonts-roboto may not be available on every runner but the above installs the standard TeXLive font packages
        shell: bash

      - name: Create .env from repository secrets
        run: |
          cat > .env <<EOF
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          ZYTE_API_KEY=${{ secrets.ZYTE_API_KEY }}
          EMAIL_SMTP_SERVER=${{ secrets.EMAIL_SMTP_SERVER }}
          EMAIL_SMTP_PORT=${{ secrets.EMAIL_SMTP_PORT }}
          EMAIL_SENDER_ADDRESS=${{ secrets.EMAIL_SENDER_ADDRESS }}
          EMAIL_SENDER_PASSWORD=${{ secrets.EMAIL_SENDER_PASSWORD }}
          EMAIL_TO=${{ secrets.EMAIL_TO }}
          EOF
        shell: bash

      - name: Ensure processed_jobs.json exists (avoid upload failure)
        run: |
          if [ ! -f processed_jobs.json ]; then
            echo "[]" > processed_jobs.json
            echo "Created empty processed_jobs.json"
          fi
        shell: bash

      - name: Run AI Job Application Assistant
        env:
          # In case your code reads env vars directly; .env is also present for load_dotenv
          PYTHONUNBUFFERED: 1
        run: python main.py
        shell: bash

      - name: Upload tracker artifact
        uses: actions/upload-artifact@v4
        with:
          name: processed-jobs-tracker
          path: processed_jobs.json
          retention-days: 30
